### PR TITLE
Update to the latest API schema

### PR DESCRIPTION
**Pull request by bernerdschaefer**
* Bring in the latest changes from the Heroku platform schema
* Update generated client with new acronyms

### CODE REVIEW

**Comment by talbright** [comment]
@joestump just a heads up, at a quick glance this looks like it might affect the work you did in the provider (only when the deps are updated of course.)

**Comment by joestump** [comment]
@talbright it's vendor'd so we're good, but I'll work up a PR for it.

**Comment by bernerdschaefer** [comment]
@joestump Ah, hmm... We should definitely be moving from Org to Team endpoints for creating apps in spaces, but that's also a potentially larger change than is strictly needed to get the field out.

I'll check with the team about whether we want to backport this field or update the provider to use the new endpoint without changing the underlying state fields from org to team. Either way, we had intended to pick up the work to add this to terraform along with developing the feature.

**Comment by joestump** [comment]
@bernerdschaefer I'm working on updating the provider now to add `team` attributes wherever there are `organization` attributes. The issue is that `organization` is marked as `ForceNew: true`. The `heroku_app` resource [uses different API endpoints](https://github.com/terraform-providers/terraform-provider-heroku/blob/master/heroku/resource_heroku_app.go#L229-L235) depending on if `organization` was specified or not. 

As it stands, you can't switch from `organization` to `team` without TF wanting to `ForceNew` on your apps. And you need to specify `team` in order to set `internal_routing = true`. 

I'm talking with @davidji99 about ways we can make this all work, but any insight would be helpful.

**Comment by joestump** [comment]
@bernerdschaefer would it be possible for us to treat the `organization` and `team` attributes as synonyms and just always use the [team app](https://devcenter.heroku.com/articles/platform-api-reference#team-app) endpoints?

**Comment by bernerdschaefer** [comment]
> I'm working on updating the provider now to add team attributes wherever there are organization attributes.

Oh, good to know!

> would it be possible for us to treat the organization and team attributes as synonyms and just always use the team app endpoints?

Yes, that's how I understand the org->team migration to work.

**Comment by joestump** [comment]
@bernerdschaefer I've opened up a WIP PR for the team work https://github.com/terraform-providers/terraform-provider-heroku/pull/86/files It'd be great to have my assumptions checked.

**Comment by talbright** [comment]
@bernerdschaefer would you be amicable to refreshing this with the latest schema changes merged in the other day?

**Comment by bernerdschaefer** [comment]
b0644dd now also includes the latest schema changes to space app access permissions.

**Comment by bernerdschaefer** [comment]
@cyberdelia I think this is ready to go whenever you're available to merge.

**Pull request merged**
